export type CailSandboxCredential = { kind:"jwt"|"key"; token:string };
export type SandboxState = "active"|"destroyed";
export interface SandboxLifecycle { id:string; state:SandboxState; expires_at:string }
export interface CommandOutputEvent { type:"stdout"|"stderr"; data:Uint8Array }
export type CommandTerminalEvent = { type:"exit"; exitCode:number } | { type:"error"; code:string; message:string; requestId:string };
export class CailSandboxError extends Error { constructor(readonly code:string,message:string,readonly status:number,readonly type:string="unknown_error",readonly param:string|null=null,readonly details:Record<string,unknown>={}){super(message);this.name="CailSandboxError";Object.setPrototypeOf(this,CailSandboxError.prototype)} }
export type FetchLike = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
export interface SandboxClientOptions { baseUrl:string; app:string; fetchImpl?:FetchLike }
const APP=/^[a-z0-9][a-z0-9-]{0,63}$/;
async function parseError(r:Response){let b:any;try{b=await r.json()}catch{return new CailSandboxError("unknown_error",`Sandbox request failed with HTTP ${r.status}.`,r.status)}const e=b?.error;return new CailSandboxError(typeof e?.code==="string"?e.code:"unknown_error",typeof e?.message==="string"?e.message:`Sandbox request failed with HTTP ${r.status}.`,r.status,typeof e?.type==="string"?e.type:"unknown_error",typeof e?.param==="string"?e.param:null,e?.cail&&typeof e.cail==="object"?e.cail:{})}
export function createCailSandboxClient(options:SandboxClientOptions){if(!options.baseUrl.startsWith("https://")&&!options.baseUrl.startsWith("http://localhost"))throw new Error("baseUrl must use HTTPS (or localhost)");if(!APP.test(options.app))throw new Error("app must be a stable lowercase slug");const f=options.fetchImpl??fetch,base=options.baseUrl.replace(/\/+$/,"");
 const call=async(path:string,init:RequestInit,credential:CailSandboxCredential)=>{const h=new Headers(init.headers);h.delete("x-cail-identity-jwt");h.set("x-cail-app",options.app);if(credential.kind==="jwt"){h.delete("authorization");h.set("x-cail-identity-jwt",credential.token)}else{h.delete("x-cail-identity-jwt");h.set("authorization",`Bearer ${credential.token}`)}const r=await f(`${base}${path}`,{...init,headers:h,redirect:"error"});if(!r.ok)throw await parseError(r);return r};
 return { call, async create(c:CailSandboxCredential){const r=await call("/sandbox/v1/sandbox",{method:"POST",headers:{"content-type":"application/json"},body:"{}"},c);return r.json() as Promise<SandboxLifecycle>}, async running(id:string,c:CailSandboxCredential){const r=await call(`/sandbox/v1/sandbox/${encodeURIComponent(id)}/running`,{},c);return r.json() as Promise<{running:boolean;state:SandboxState;expires_at:string}>}, async destroy(id:string,c:CailSandboxCredential){await call(`/sandbox/v1/sandbox/${encodeURIComponent(id)}`,{method:"DELETE"},c)}, async createSession(id:string,c:CailSandboxCredential){const r=await call(`/sandbox/v1/sandbox/${encodeURIComponent(id)}/session`,{method:"POST"},c);return r.json() as Promise<{id:string}>}, async destroySession(id:string,sid:string,c:CailSandboxCredential){await call(`/sandbox/v1/sandbox/${encodeURIComponent(id)}/session/${encodeURIComponent(sid)}`,{method:"DELETE"},c)}, async readFile(id:string,path:string,c:CailSandboxCredential){return call(`/sandbox/v1/sandbox/${encodeURIComponent(id)}/file/${encodePath(path)}`,{},c)}, async writeFile(id:string,path:string,body:BodyInit,c:CailSandboxCredential){await call(`/sandbox/v1/sandbox/${encodeURIComponent(id)}/file/${encodePath(path)}`,{method:"PUT",body},c)}, async exec(id:string,command:string,c:CailSandboxCredential,opts:{sessionId?:string;signal?:AbortSignal}={}){const r=await call(`/sandbox/v1/sandbox/${encodeURIComponent(id)}/exec`,{method:"POST",headers:{"content-type":"application/json","accept":"text/event-stream"},body:JSON.stringify({command,...(opts.sessionId?{session_id:opts.sessionId}:{})}),signal:opts.signal},c);return parseCommandEvents(r)}, async openapi(c:CailSandboxCredential){const r=await call("/sandbox/v1/openapi.json",{},c);return r.json() as Promise<Record<string,unknown>>} };
}
function encodePath(p:string){if(p.startsWith("/")||p.split("/").some(x=>x===".."))throw new Error("file path must be workspace-relative");return p.split("/").map(encodeURIComponent).join("/")}
async function* parseCommandEvents(response:Response):AsyncGenerator<CommandOutputEvent|CommandTerminalEvent>{if(!response.body)throw new CailSandboxError("invalid_stream","Command response had no body.",response.status);const reader=response.body.pipeThrough(new TextDecoderStream()).getReader();let buf="",terminal=false;while(true){const {done,value}=await reader.read();buf+=value??"";let i;while((i=buf.indexOf("\n\n"))>=0){const raw=buf.slice(0,i);buf=buf.slice(i+2);const event=/^event: (.+)$/m.exec(raw)?.[1],data=/^data: (.+)$/m.exec(raw)?.[1];if(!event||!data)continue;const d=JSON.parse(data);if(event==="stdout"||event==="stderr"){if(terminal)throw new CailSandboxError("invalid_stream","Output followed the terminal event.",response.status);yield {type:event,data:Uint8Array.from(atob(d.data),x=>x.charCodeAt(0))}}else if(event==="exit"){if(terminal)throw new CailSandboxError("invalid_stream","Command stream had multiple terminal events.",response.status);terminal=true;yield {type:"exit",exitCode:d.exit_code}}else if(event==="error"){if(terminal)throw new CailSandboxError("invalid_stream","Command stream had multiple terminal events.",response.status);terminal=true;yield {type:"error",code:d.code,message:d.message,requestId:d.request_id}}}if(done)break}if(!terminal)throw new CailSandboxError("invalid_stream","Command stream ended without a terminal event.",response.status)}
